publication_home:
    path: /
    defaults: {_controller: PublicationBundle:Publication:index}

publication_add:
    path: /ajout-sujet
    defaults: {_controller: PublicationBundle:Publication:add}

publication_view_sujet:
    path: /view-sujet-{id}
    defaults: { _controller: PublicationBundle:Publication:viewSujet }

publication_edit:
    path: /edit-sujet-{id}
    defaults: { _controller: PublicationBundle:Publication:edit }

publication_delete:
    path: /delete-sujet-{id}
    defaults: { _controller: PublicationBundle:Publication:delete }
